from __future__ import annotations

import argparse
from pathlib import Path

from src.attacks.poison_utils import evaluate_response_shift, retrieve_chunks_lexical, write_rows_to_csv
from src.generation.generate_responses import DEFAULT_LOCAL_ENDPOINT, call_generation_model, source_refs
from src.rag.embed import DEFAULT_MODEL, load_embedding_model
from src.rag.retrieve import format_retrieved_context, retrieve_chunks
from src.utils.helpers import project_root, read_json, vector_store_dir, write_json
from src.utils.prompt_templates import build_survey_response_prompt


def default_results_dir() -> Path:
    return project_root() / "results"


def load_clean_chunk_ids(metadata_path: Path) -> set[str]:
    if not metadata_path.exists():
        raise FileNotFoundError(f"Missing clean metadata file: {metadata_path}")

    payload = read_json(metadata_path)
    if not isinstance(payload, list):
        raise ValueError(f"Expected metadata JSON array in {metadata_path}")
    return {str(chunk.get("chunk_id")) for chunk in payload if chunk.get("chunk_id")}


def generate_with_chunks(
    question: str,
    persona: dict | None,
    chunks: list[dict],
    provider: str,
    model: str | None,
    local_endpoint: str,
    dry_run: bool,
) -> dict:
    context = format_retrieved_context(chunks) if chunks else "No retrieved context provided."
    prompt = build_survey_response_prompt(question=question, retrieved_context=context, persona=persona)
    response = ""
    if not dry_run:
        response = call_generation_model(
            prompt=prompt,
            provider=provider,
            model=model,
            local_endpoint=local_endpoint,
        )
    return {"prompt": prompt, "response": response}


def parse_args() -> argparse.Namespace:
    results_dir = default_results_dir()
    parser = argparse.ArgumentParser(description="Apply defense checks against poisoned retrieval influence.")
    parser.add_argument(
        "--attack-records",
        type=Path,
        default=results_dir / "attack_responses.json",
        help="Attack comparison records JSON generated by run_attack.py",
    )
    parser.add_argument(
        "--clean-metadata-path",
        type=Path,
        default=vector_store_dir() / "rag_metadata.json",
        help="Trusted clean metadata JSON.",
    )
    parser.add_argument(
        "--poison-index-path",
        type=Path,
        default=results_dir / "poisoned_vector_store" / "rag_index.faiss",
        help="Poisoned FAISS index path.",
    )
    parser.add_argument(
        "--poison-metadata-path",
        type=Path,
        default=results_dir / "poisoned_vector_store" / "rag_metadata.json",
        help="Poisoned metadata JSON path.",
    )
    parser.add_argument("--top-k", type=int, default=3, help="Fallback top-k if attack record does not include it.")
    parser.add_argument("--provider", default=None, choices=("groq", "local", "openai"), help="Override provider.")
    parser.add_argument("--model", default=None, help="Override model name.")
    parser.add_argument("--local-endpoint", default=DEFAULT_LOCAL_ENDPOINT, help="Local Ollama-compatible endpoint.")
    parser.add_argument("--embedding-model", default=DEFAULT_MODEL, help="Embedding model for divergence scoring.")
    parser.add_argument(
        "--semantic-threshold",
        type=float,
        default=10.0,
        help="Semantic shift threshold for suspicious divergence.",
    )
    parser.add_argument(
        "--output-json",
        type=Path,
        default=results_dir / "defense_results.json",
        help="JSON path for defense records.",
    )
    parser.add_argument(
        "--output-csv",
        type=Path,
        default=results_dir / "defense_results.csv",
        help="CSV path for defense records.",
    )
    parser.add_argument("--dry-run", action="store_true", help="Skip LLM calls and only run retrieval/filter logic.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.attack_records.exists():
        raise FileNotFoundError(f"Attack records file does not exist: {args.attack_records}")
    if not args.poison_index_path.exists():
        raise FileNotFoundError(f"Poisoned index file does not exist: {args.poison_index_path}")
    if not args.poison_metadata_path.exists():
        raise FileNotFoundError(f"Poisoned metadata file does not exist: {args.poison_metadata_path}")

    attack_records = read_json(args.attack_records)
    if not isinstance(attack_records, list):
        raise ValueError(f"Expected list payload in {args.attack_records}")

    clean_chunk_ids = load_clean_chunk_ids(args.clean_metadata_path)
    embedding_model = None if args.dry_run else load_embedding_model(args.embedding_model)
    poisoned_metadata = read_json(args.poison_metadata_path) if args.dry_run else None

    defense_rows: list[dict] = []

    for record in attack_records:
        question = str(record.get("question") or record.get("prompt") or "").strip()
        if not question:
            continue

        persona = record.get("persona") if isinstance(record.get("persona"), dict) else None
        domain = record.get("domain")
        provider = args.provider or str(record.get("provider") or "groq")
        model = args.model or (record.get("model") if isinstance(record.get("model"), str) else None)
        top_k = int(record.get("top_k") or args.top_k)

        if args.dry_run:
            if not isinstance(poisoned_metadata, list):
                raise ValueError(f"Expected metadata JSON array in {args.poison_metadata_path}")
            poisoned_chunks = retrieve_chunks_lexical(
                query=question,
                metadata=poisoned_metadata,
                top_k=top_k,
                domain=domain,
            )
        else:
            poisoned_chunks = retrieve_chunks(
                query=question,
                top_k=top_k,
                domain=domain,
                index_path=args.poison_index_path,
                metadata_path=args.poison_metadata_path,
            )
        trusted_chunks = [chunk for chunk in poisoned_chunks if str(chunk.get("chunk_id")) in clean_chunk_ids]
        untrusted_chunks = [chunk for chunk in poisoned_chunks if str(chunk.get("chunk_id")) not in clean_chunk_ids]

        with_context = generate_with_chunks(
            question=question,
            persona=persona,
            chunks=poisoned_chunks,
            provider=provider,
            model=model,
            local_endpoint=args.local_endpoint,
            dry_run=args.dry_run,
        )
        filtered_context = generate_with_chunks(
            question=question,
            persona=persona,
            chunks=trusted_chunks,
            provider=provider,
            model=model,
            local_endpoint=args.local_endpoint,
            dry_run=args.dry_run,
        )

        divergence = evaluate_response_shift(
            baseline_text=with_context["response"],
            attacked_text=filtered_context["response"],
            threshold_pct=args.semantic_threshold,
            embedding_model_name=args.embedding_model,
            embedding_model=embedding_model,
        )
        suspicious = bool(untrusted_chunks) or divergence["semantic_shift_pct"] > args.semantic_threshold

        reasons: list[str] = []
        if untrusted_chunks:
            reasons.append("untrusted_retrieval_sources")
        if divergence["semantic_shift_pct"] > args.semantic_threshold:
            reasons.append("high_context_divergence")
        suspicion_reason = ", ".join(reasons) if reasons else "none"

        defended_response = filtered_context["response"] if suspicious else with_context["response"]
        defense_action = "use_filtered_context" if suspicious else "keep_retrieved_context"

        defense_rows.append(
            {
                "persona_id": record.get("persona_id"),
                "persona": persona,
                "prompt": question,
                "question": question,
                "domain": domain,
                "provider": provider,
                "model": model,
                "top_k": top_k,
                "baseline_response": record.get("baseline_response"),
                "attacked_response": record.get("attacked_response"),
                "context_response": with_context["response"],
                "filtered_response": filtered_context["response"],
                "defended_response": defended_response,
                "suspicious": suspicious,
                "suspicion_reason": suspicion_reason,
                "defense_action": defense_action,
                "untrusted_source_count": len(untrusted_chunks),
                "response_similarity_context_vs_filtered": divergence["response_similarity"],
                "semantic_shift_context_vs_filtered_pct": divergence["semantic_shift_pct"],
                "keyword_shift_context_vs_filtered_pct": divergence["keyword_shift_pct"],
                "poisoned_retrieved_sources": source_refs(poisoned_chunks),
                "trusted_retrieved_sources": source_refs(trusted_chunks),
                "context_prompt": with_context["prompt"],
                "filtered_prompt": filtered_context["prompt"],
            }
        )

    write_json(args.output_json, defense_rows)
    write_rows_to_csv(
        args.output_csv,
        defense_rows,
        fieldnames=[
            "persona_id",
            "prompt",
            "domain",
            "provider",
            "model",
            "top_k",
            "baseline_response",
            "attacked_response",
            "context_response",
            "filtered_response",
            "defended_response",
            "suspicious",
            "suspicion_reason",
            "defense_action",
            "untrusted_source_count",
            "response_similarity_context_vs_filtered",
            "semantic_shift_context_vs_filtered_pct",
            "keyword_shift_context_vs_filtered_pct",
            "poisoned_retrieved_sources",
            "trusted_retrieved_sources",
        ],
    )

    print(f"Wrote {len(defense_rows)} defense records to {args.output_json}")
    print(f"Wrote defense table to {args.output_csv}")


if __name__ == "__main__":
    main()
